### ISSUE TITLE
It is not working with django-cms v3 and django 1.6.2

### ISSUE THREAD

**Issue by erieval** [theherk/django-theherk-events#1]
I have django-cms v3 with django 1.6.2.  I installed django-theherk-events and get this error with python manage.py migrate events command:
from django.contrib.localflavor.us.models import USStateField
ImportError: No module named localflavor.us.models
Here is the full paste of the error: http://paste.debian.net/91195/
Thanks

**Comment by theherk** [comment]
It looks like localflavor was removed from contrib in Django 1.6. It looks like you can get django-localflavor from pypi then change the import to `from localflavor.us.models import USStateField`.

Sources:
http://stackoverflow.com/questions/18214624/django-1-6b-gis-import-error
http://stackoverflow.com/questions/15277688/how-to-fix-localflavor-deprecation-warning-in-django-1-5

**Comment by erieval** [comment]
I installed django-localflavor from pypi and made changes to contact_types.py:
from localflavor.us.models import USStateField
from localflavor.us.models import PhoneNumberField
from localflavor.us.us_states import USPS_CHOICES

I am still getting errors when trying to migrate events: 

CommandError: One or more models did not validate:
events.event: 'location' has a relation with model <class 'resources.models.organizations.Organization'>, which has either not been installed or is abstract.
events.event: 'contact' has a relation with model <class 'resources.models.people.Person'>, which has either not been installed or is abstract.

I am not really a programmer and not sure how to deal with that error.
Would it be possible to upgrade the plugin to use with django-cms v3 and django 1.6.2 ?

**Comment by theherk** [comment]
Hmm, perhaps. I will be looking into this today. I haven't dealt with these components for some time, but you caught me as I am actually having to put some effort into it. Looking through the code, I recall that it depends on [django-theherk-resources](https://github.com/theherk/django-theherk-resources). Sorry, I'm not a pro and I failed to include that dependency. It is what allows you to manage the locations and contacts for the events.

If you want to see it in action, check out [kansas.responders.us](http://kansas.responders.us/), and see the Upcoming Events on the right or Events at the top.

**Comment by erieval** [comment]
I included 'resources' in INSTALLED_APPS and still getting errors when
migrating the app.
We have here django-cms 3 (with django 1.6) and no events or contact app
since everything we tried already available is not working with these
versions.
It would be great if django-theherk-events will be upgraded to work with
django 1.6   It looks pretty godd at kansas.responders.us
Thanks for responding

**Comment by theherk** [comment]
I don't know what you timeline is, so I hate to make any guarantees, but I hope to get this done very soon. I am working on it today.

**Comment by erieval** [comment]
Thanks.
That would be great :)
Any help is greatly appreciated

**Comment by theherk** [comment]
Oh no! I didn't catch the django-cms version. I figured it was a minor change for a Django update. django-cms 3 isn't even released yet. Ha, you are pushing me forward; I dig it. I don't know the ramifications of trying to get it to work with v3, but I'm working on it.

**Comment by theherk** [comment]
You should be good to go. Remove both django-theherk-events and django-theherk-resources, then just install django-theherk-events from PyPI (it will pull django-theherk-resources).

Tested with:
- Django 1.6.2
- django-cms 3.0c1
- django-localflavor

Close with 4622125a0f

**Comment by theherk** [comment]
Also, as a note, check out [4.3.3. Automatically restart server on apphook changes](http://docs.django-cms.org/en/develop/extending_cms/app_integration.html#automatically-restart-server-on-apphook-changes). Anytime you add, remove, or move an apphook, you need to restart the application.

**Comment by erieval** [comment]
I assume that there is an automatic email with every opened issue, but
decided to write the email anyway.
I am still getting error, although I can see the app as an available plugin
and can hook it to a page.
I did open new issue at
https://github.com/theherk/django-theherk-events/issues/2, where you can
see all the detals of error
I wish I was as good in programming as in opening issues : )
Thanks
